spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://unisphere-team:Shashi2002@cluster0.aja2e.mongodb.net/SmartCampusDB?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=SmartCampusDB