spring.application.name=UniSphere-Smart-Campus-API

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://unisphere-team:Shashi2002@cluster0.aja2e.mongodb.net/SmartCampusDB?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=SmartCampusDB

# Server Configuration
server.port=8081

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.unisphere=DEBUG

# CORS (handled programmatically)
