spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/unisphere_db_dev
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate

logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.unisphere=DEBUG
